### ISSUE TITLE
Module 3 & 5: OSError: [E050] Can't find model 'en_core_web_sm'

### ISSUE THREAD

**Issue by vdavis3** [dlab-berkeley/Data-Science-Social-Justice#27]
Add line to fix:
!python -m spacy download en_core_web_sm

**Comment by jellomoat** [comment]
Code block 9 in the [lesson notebook](https://github.com/dlab-berkeley/Data-Science-Social-Justice/blob/main/lessons/module-3/Preprocessing_Lesson.ipynb) already has this commented segment, instructing folks to uncomment to install during the lesson:

```
# Uncomment the following lines to install spaCy and language pipeline

#%pip install -U pydantic spacy
#!python -m spacy download en_core_web_sm

```
